-- PostgreSQL schema generated from Django migrations. Migrations are authoritative: run `manage.py migrate`.

-- contenttypes.0001_initial
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");

-- contenttypes.0002_remove_content_type_name
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name";

-- auth.0001_initial
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
-- (no-op)
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");

-- auth.0002_alter_permission_name_max_length
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);

-- auth.0003_alter_user_email_max_length
--
-- Alter field email on user
--
-- (no-op)

-- auth.0004_alter_user_username_opts
--
-- Alter field username on user
--
-- (no-op)

-- auth.0005_alter_user_last_login_null
--
-- Alter field last_login on user
--
-- (no-op)

-- auth.0006_require_contenttypes_0002


-- auth.0007_alter_validators_add_error_messages
--
-- Alter field username on user
--
-- (no-op)

-- auth.0008_alter_user_username_max_length
--
-- Alter field username on user
--
-- (no-op)

-- auth.0009_alter_user_last_name_max_length
--
-- Alter field last_name on user
--
-- (no-op)

-- auth.0010_alter_group_name_max_length
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);

-- auth.0011_update_proxy_permissions
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL

-- auth.0012_alter_user_first_name_max_length
--
-- Alter field first_name on user
--
-- (no-op)

-- shop.0001_initial
--
-- Create model Product
--
CREATE TABLE "shop_product" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "description" text NOT NULL, "price" numeric(10, 2) NOT NULL, "stock" integer NOT NULL CHECK ("stock" >= 0), "weight_lb" numeric(6, 2) NOT NULL, "length_in" numeric(6, 2) NOT NULL, "width_in" numeric(6, 2) NOT NULL, "height_in" numeric(6, 2) NOT NULL, "is_active" boolean NOT NULL, "created" timestamp with time zone NOT NULL, "updated" timestamp with time zone NOT NULL);
--
-- Create model SiteSettings
--
CREATE TABLE "shop_sitesettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "site_name" varchar(100) NOT NULL, "commission_percent" numeric(5, 2) NOT NULL, "allow_seller_signup" boolean NOT NULL, "chatbot_enabled" boolean NOT NULL);
--
-- Create model User
--
CREATE TABLE "shop_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "role" varchar(10) NOT NULL);
CREATE TABLE "shop_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "shop_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model Order
--
CREATE TABLE "shop_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar(20) NOT NULL, "ship_name" varchar(120) NOT NULL, "ship_line1" varchar(200) NOT NULL, "ship_city" varchar(100) NOT NULL, "ship_state" varchar(2) NOT NULL, "ship_zip" varchar(10) NOT NULL, "shipping_service" varchar(40) NOT NULL, "shipping_cost" numeric(10, 2) NOT NULL, "subtotal" numeric(12, 2) NOT NULL, "total" numeric(12, 2) NOT NULL, "tracking_number" varchar(40) NOT NULL, "return_reason" text NOT NULL, "created" timestamp with time zone NOT NULL, "updated" timestamp with time zone NOT NULL, "customer_id" bigint NOT NULL);
--
-- Create model OrderItem
--
CREATE TABLE "shop_orderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "product_name" varchar(200) NOT NULL, "unit_price" numeric(10, 2) NOT NULL, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "order_id" bigint NOT NULL, "product_id" bigint NOT NULL);
--
-- Create model Message
--
CREATE TABLE "shop_message" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "body" text NOT NULL, "created" timestamp with time zone NOT NULL, "read" boolean NOT NULL, "recipient_id" bigint NOT NULL, "sender_id" bigint NOT NULL, "order_id" bigint NULL, "product_id" bigint NULL);
--
-- Create model ProductImage
--
CREATE TABLE "shop_productimage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "image" varchar(100) NOT NULL, "created" timestamp with time zone NOT NULL, "product_id" bigint NOT NULL);
--
-- Create model Store
--
CREATE TABLE "shop_store" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "description" text NOT NULL, "is_active" boolean NOT NULL, "created" timestamp with time zone NOT NULL, "owner_id" bigint NOT NULL UNIQUE);
--
-- Add field store to product
--
ALTER TABLE "shop_product" ADD COLUMN "store_id" bigint NOT NULL CONSTRAINT "shop_product_store_id_a6f6a616_fk_shop_store_id" REFERENCES "shop_store"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "shop_product_store_id_a6f6a616_fk_shop_store_id" IMMEDIATE;
--
-- Add field store to order
--
ALTER TABLE "shop_order" ADD COLUMN "store_id" bigint NOT NULL CONSTRAINT "shop_order_store_id_b64955cb_fk_shop_store_id" REFERENCES "shop_store"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "shop_order_store_id_b64955cb_fk_shop_store_id" IMMEDIATE;
--
-- Create model CartItem
--
CREATE TABLE "shop_cartitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "user_id" bigint NOT NULL, "product_id" bigint NOT NULL, CONSTRAINT "unique_cart_line" UNIQUE ("user_id", "product_id"));
--
-- Create constraint product_price_positive on model product
--
ALTER TABLE "shop_product" ADD CONSTRAINT "product_price_positive" CHECK ("price" > 0);
CREATE INDEX "shop_product_name_b8d5e94c" ON "shop_product" ("name");
CREATE INDEX "shop_product_name_b8d5e94c_like" ON "shop_product" ("name" varchar_pattern_ops);
CREATE INDEX "shop_user_username_0b1fc3cb_like" ON "shop_user" ("username" varchar_pattern_ops);
CREATE INDEX "shop_user_email_2e06710f_like" ON "shop_user" ("email" varchar_pattern_ops);
ALTER TABLE "shop_user_groups" ADD CONSTRAINT "shop_user_groups_user_id_group_id_29c349c0_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "shop_user_groups" ADD CONSTRAINT "shop_user_groups_user_id_252129d6_fk_shop_user_id" FOREIGN KEY ("user_id") REFERENCES "shop_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shop_user_groups" ADD CONSTRAINT "shop_user_groups_group_id_bf3fb67c_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_user_groups_user_id_252129d6" ON "shop_user_groups" ("user_id");
CREATE INDEX "shop_user_groups_group_id_bf3fb67c" ON "shop_user_groups" ("group_id");
ALTER TABLE "shop_user_user_permissions" ADD CONSTRAINT "shop_user_user_permissions_user_id_permission_id_8836bbbf_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "shop_user_user_permissions" ADD CONSTRAINT "shop_user_user_permissions_user_id_d5f91630_fk_shop_user_id" FOREIGN KEY ("user_id") REFERENCES "shop_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shop_user_user_permissions" ADD CONSTRAINT "shop_user_user_permi_permission_id_ace4643b_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_user_user_permissions_user_id_d5f91630" ON "shop_user_user_permissions" ("user_id");
CREATE INDEX "shop_user_user_permissions_permission_id_ace4643b" ON "shop_user_user_permissions" ("permission_id");
ALTER TABLE "shop_order" ADD CONSTRAINT "shop_order_customer_id_f638df20_fk_shop_user_id" FOREIGN KEY ("customer_id") REFERENCES "shop_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_order_status_16691b37" ON "shop_order" ("status");
CREATE INDEX "shop_order_status_16691b37_like" ON "shop_order" ("status" varchar_pattern_ops);
CREATE INDEX "shop_order_created_08bc3422" ON "shop_order" ("created");
CREATE INDEX "shop_order_customer_id_f638df20" ON "shop_order" ("customer_id");
ALTER TABLE "shop_orderitem" ADD CONSTRAINT "shop_orderitem_order_id_2f1b00cf_fk_shop_order_id" FOREIGN KEY ("order_id") REFERENCES "shop_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shop_orderitem" ADD CONSTRAINT "shop_orderitem_product_id_48153f22_fk_shop_product_id" FOREIGN KEY ("product_id") REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_orderitem_order_id_2f1b00cf" ON "shop_orderitem" ("order_id");
CREATE INDEX "shop_orderitem_product_id_48153f22" ON "shop_orderitem" ("product_id");
ALTER TABLE "shop_message" ADD CONSTRAINT "shop_message_recipient_id_0115c38a_fk_shop_user_id" FOREIGN KEY ("recipient_id") REFERENCES "shop_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shop_message" ADD CONSTRAINT "shop_message_sender_id_04755c7b_fk_shop_user_id" FOREIGN KEY ("sender_id") REFERENCES "shop_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shop_message" ADD CONSTRAINT "shop_message_order_id_d82c459a_fk_shop_order_id" FOREIGN KEY ("order_id") REFERENCES "shop_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shop_message" ADD CONSTRAINT "shop_message_product_id_c3f2f0ad_fk_shop_product_id" FOREIGN KEY ("product_id") REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_message_created_3185a02a" ON "shop_message" ("created");
CREATE INDEX "shop_message_recipient_id_0115c38a" ON "shop_message" ("recipient_id");
CREATE INDEX "shop_message_sender_id_04755c7b" ON "shop_message" ("sender_id");
CREATE INDEX "shop_message_order_id_d82c459a" ON "shop_message" ("order_id");
CREATE INDEX "shop_message_product_id_c3f2f0ad" ON "shop_message" ("product_id");
ALTER TABLE "shop_productimage" ADD CONSTRAINT "shop_productimage_product_id_65b3b20c_fk_shop_product_id" FOREIGN KEY ("product_id") REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_productimage_product_id_65b3b20c" ON "shop_productimage" ("product_id");
ALTER TABLE "shop_store" ADD CONSTRAINT "shop_store_owner_id_1d0c493c_fk_shop_user_id" FOREIGN KEY ("owner_id") REFERENCES "shop_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_store_name_ed871d77_like" ON "shop_store" ("name" varchar_pattern_ops);
CREATE INDEX "shop_product_store_id_a6f6a616" ON "shop_product" ("store_id");
CREATE INDEX "shop_order_store_id_b64955cb" ON "shop_order" ("store_id");
ALTER TABLE "shop_cartitem" ADD CONSTRAINT "shop_cartitem_user_id_5a7eba01_fk_shop_user_id" FOREIGN KEY ("user_id") REFERENCES "shop_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "shop_cartitem" ADD CONSTRAINT "shop_cartitem_product_id_09e4b7dd_fk_shop_product_id" FOREIGN KEY ("product_id") REFERENCES "shop_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "shop_cartitem_user_id_5a7eba01" ON "shop_cartitem" ("user_id");
CREATE INDEX "shop_cartitem_product_id_09e4b7dd" ON "shop_cartitem" ("product_id");
